FROM registry.cn-shenzhen.aliyuncs.com/jxqwe/base:nginx
MAINTAINER chenshanping
WORKDIR /var/www/book-frontend
COPY frontend/dist /var/www/book-frontend
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80 443