mysql:
  host: "11.0.1.70"
  user: "root"
  password: "123456"
  port: 3306
  dbname: "bookManger"
minio:
  host: "11.0.1.70"
  user: "admin"
  password: "guLI6j27"
  port: 9001
# zap logger configuration
zap:
  level: "info"
  format: 'console'
  prefix: '[GIN-VUE-ADMIN]'
  director: 'log'
  link-name: 'latest_log'
  show-line: true
  encode-level: 'LowercaseColorLevelEncoder'
  stacktrace-key: 'stacktrace'
  log-in-console: true
