mysql:
  host: "11.0.1.70"
  user: "root"
  password: "123456"
  port: 3306
  dbname: "bookManger"
redis:
  host: "11.0.1.70"
  port: 6379
  password: "4ZQok8ws"
  db: 1
system:
  host: "localhost"
  port: "8080"
  env: "dev"
  
